project:
  type: website
  output-dir: docs
  
website:
  title: "Website1"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

